### ISSUE TITLE
Area lights are frustum culled incorrectly

### ISSUE THREAD

**Issue by artyom-zuev** [Unity-Technologies/VolumetricLighting#1]
As soon as area light source moves out of the camera frustum, it is disabled, which is obviously undesireable behaviour - instead, it would be nice to have culling similar to bounds based one used for mesh renderers (using XYZ box of the area light as a reference, for example). Can anyone point me to a way to adjust how culling works on area lights?

**Comment by robertcupisz** [comment]
Take a look at the comment in AreaLight.cs:134

Currently the area lights are bound to a frustum when the shadows are enabled, and completely unbounded with their influence otherwise. In the former case the culling should work correctly, more or less. In the latter - it will currently behave incorrectly.

The proper way to fix this would be to make area lights have a finite range of influence (which will make them "less" physically correct, but is a necessary evil), and define bounds, which conservatively encompass that range.

Currently I can't invest time in this, but it might be worth following https://github.com/Unity-Technologies/ScriptableRenderLoop, since that's where we put the latest implementations of new unity light types.

**Comment by artyom-zuev** [comment]
Thanks for the info! 
Will definitely follow that repository too. :)

**Comment by robertcupisz** [comment]
Cheers :)
