### ISSUE TITLE
FindObjectOfType keeps getting called every frame

### ISSUE THREAD

**Issue by VinQbator** [Unity-Technologies/VolumetricLighting#2]
`static LightManager<T> Instance` in LightManager.cs is calling FindObjectOfType() every frame if there is no LightManagerFogEllipsoids in scene, which causes high CPU use.

**Comment by robertcupisz** [comment]
The intention is that a LightManager is placed manually in the scene, just like in the example scenes.

The reason is that with the current callback system - particularly when rendering in edit mode in the scene view - it's difficult to ensure that the light manager always gets created and destroyed at the right time.
